import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    success: true,
    endpoint: '/api/pricing',
    currency: 'USD',
    billing_cycles: ['monthly', 'annual'],
    annual_discount_pct: 20,
    plans: [
      {
        id: 'free',
        name: 'Free',
        price_monthly: 0,
        price_annual: 0,
        features: {
          qrons_per_month: 50,
          scans_per_month: 500,
          scan_tracking: false,
          custom_domains: 0,
          ai_styles: false,
          bulk_create: false,
          api_access: false,
          white_label: false,
          support: 'community',
        },
        cta: 'Get Started Free',
        popular: false,
      },
      {
        id: 'starter',
        name: 'Starter',
        price_monthly: 29,
        price_annual: 23,
        features: {
          qrons_per_month: 500,
          scans_per_month: 10000,
          scan_tracking: true,
          custom_domains: 1,
          ai_styles: false,
          bulk_create: false,
          api_access: true,
          white_label: false,
          support: 'email',
        },
        cta: 'Start Free Trial',
        popular: false,
      },
      {
        id: 'professional',
        name: 'Professional',
        price_monthly: 99,
        price_annual: 79,
        features: {
          qrons_per_month: 10000,
          scans_per_month: 250000,
          scan_tracking: true,
          custom_domains: 3,
          ai_styles: true,
          bulk_create: true,
          api_access: true,
          white_label: false,
          support: 'priority_email',
        },
        cta: 'Start Free Trial',
        popular: true,
        badge: 'Most Popular',
      },
      {
        id: 'enterprise',
        name: 'Enterprise',
        price_monthly: 499,
        price_annual: 399,
        features: {
          qrons_per_month: 'unlimited',
          scans_per_month: 'unlimited',
          scan_tracking: true,
          custom_domains: 'unlimited',
          ai_styles: true,
          bulk_create: true,
          api_access: true,
          white_label: true,
          support: 'dedicated_csm',
          sso: true,
          sla: '99.9%',
        },
        cta: 'Contact Sales',
        popular: false,
      },
    ],
    add_ons: [
      { id: 'extra_qrons_1000', name: '1,000 Extra QRONs', price_monthly: 9, description: 'Add 1,000 more QRONs to any plan' },
      { id: 'extra_domain', name: 'Custom Domain', price_monthly: 5, description: 'Add a custom domain to any plan' },
      { id: 'white_label', name: 'White Label', price_monthly: 49, description: 'Remove QRON branding' },
    ],
    protocol: 'QRON',
  });
}
