import { NextRequest, NextResponse } from 'next/server';

const PLANS = [
  {
    id: 'free',
    name: 'Free',
    tagline: 'Try QRON with no commitment',
    price_monthly: 0,
    price_annual: 0,
    annual_savings: 0,
    stripe_price_id_monthly: null,
    stripe_price_id_annual: null,
    popular: false,
    qr_codes_limit: 5,
    scans_per_month: 500,
    ai_styles: 0,
    campaigns: 0,
    team_members: 1,
    custom_domains: 0,
    api_access: false,
    analytics: 'basic',
    features: [
      '5 QR codes',
      '500 scans/month',
      'Static & dynamic QR codes',
      'Basic scan analytics',
      '1 user',
    ],
    cta: 'Get Started Free',
    trial_days: 0,
    checkout_url: 'https://qron.space/signup',
    trial_url: null,
  },
  {
    id: 'starter',
    name: 'Starter',
    tagline: 'For individuals and small teams',
    price_monthly: 19,
    price_annual: 15,
    annual_savings: 48,
    stripe_price_id_monthly: 'price_qron_starter_monthly',
    stripe_price_id_annual: 'price_qron_starter_annual',
    popular: false,
    qr_codes_limit: 50,
    scans_per_month: 10000,
    ai_styles: 5,
    campaigns: 5,
    team_members: 2,
    custom_domains: 1,
    api_access: false,
    analytics: 'standard',
    features: [
      '50 QR codes',
      '10,000 scans/month',
      '5 AI art styles',
      '5 campaigns',
      '2 team members',
      '1 custom domain',
      'Standard analytics',
    ],
    cta: 'Start Free Trial',
    trial_days: 14,
    checkout_url: 'https://qron.space/checkout?plan=starter',
    trial_url: 'https://qron.space/trial?plan=pro_trial',
  },
  {
    id: 'pro',
    name: 'Pro',
    tagline: 'For professionals who need AI styling and full analytics',
    price_monthly: 49,
    price_annual: 39,
    annual_savings: 120,
    stripe_price_id_monthly: 'price_qron_pro_monthly',
    stripe_price_id_annual: 'price_qron_pro_annual',
    popular: true,
    qr_codes_limit: 500,
    scans_per_month: 50000,
    ai_styles: 50,
    campaigns: 20,
    team_members: 5,
    custom_domains: 2,
    api_access: true,
    analytics: 'advanced',
    features: [
      '500 QR codes',
      '50,000 scans/month',
      '50 AI art styles',
      '20 campaigns',
      '5 team members',
      '2 custom domains',
      'Advanced analytics',
      'API access',
      'A/B testing',
    ],
    cta: 'Start Free Trial',
    trial_days: 14,
    checkout_url: 'https://qron.space/checkout?plan=pro',
    trial_url: 'https://qron.space/trial?plan=pro_trial',
  },
  {
    id: 'business',
    name: 'Business',
    tagline: 'For agencies and high-volume teams',
    price_monthly: 129,
    price_annual: 103,
    annual_savings: 312,
    stripe_price_id_monthly: 'price_qron_business_monthly',
    stripe_price_id_annual: 'price_qron_business_annual',
    popular: false,
    qr_codes_limit: 5000,
    scans_per_month: 500000,
    ai_styles: -1,
    campaigns: 200,
    team_members: 25,
    custom_domains: 10,
    api_access: true,
    analytics: 'enterprise',
    features: [
      '5,000 QR codes',
      '500,000 scans/month',
      'Unlimited AI art styles',
      '200 campaigns',
      '25 team members',
      '10 custom domains',
      'Enterprise analytics',
      'White-label portal',
      'Priority support',
      'Bulk QR generation',
    ],
    cta: 'Start Free Trial',
    trial_days: 14,
    checkout_url: 'https://qron.space/checkout?plan=business',
    trial_url: 'https://qron.space/trial?plan=business_trial',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tagline: 'Custom solutions for large organizations',
    price_monthly: null,
    price_annual: null,
    annual_savings: null,
    stripe_price_id_monthly: null,
    stripe_price_id_annual: null,
    popular: false,
    qr_codes_limit: -1,
    scans_per_month: -1,
    ai_styles: -1,
    campaigns: -1,
    team_members: -1,
    custom_domains: -1,
    api_access: true,
    analytics: 'custom',
    features: [
      'Unlimited everything',
      'Custom AI model training',
      'Dedicated infrastructure',
      'SSO / SAML',
      'Custom SLA',
      'Dedicated account manager',
      'SOC 2 reports',
      'Net-30 invoicing',
    ],
    cta: 'Contact Sales',
    trial_days: 30,
    checkout_url: null,
    trial_url: null,
    contact_url: 'https://qron.space/enterprise',
  },
];

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const billing = searchParams.get('billing') || 'monthly';
  const isAnnual = billing === 'annual';

  const plans_with_billing = PLANS.map((plan) => ({
    ...plan,
    displayed_price: plan.price_monthly !== null
      ? isAnnual ? plan.price_annual : plan.price_monthly
      : null,
    billing_cycle: billing,
    active_stripe_price_id: isAnnual
      ? plan.stripe_price_id_annual
      : plan.stripe_price_id_monthly,
  }));

  return NextResponse.json({
    success: true,
    billing,
    annual_discount_percent: 20,
    plans: plans_with_billing,
    add_ons: [
      { id: 'extra_qr_100', name: 'Extra 100 QR codes', price: 5, unit: 'month' },
      { id: 'extra_scans_50k', name: 'Extra 50,000 scans', price: 9, unit: 'month' },
      { id: 'extra_ai_10', name: 'Extra 10 AI styles', price: 7, unit: 'month' },
      { id: 'onboarding', name: 'Guided onboarding session', price: 0, unit: 'one-time', note: 'Free for all plans' },
    ],
    faq: [
      { q: 'Do I need a credit card for the trial?', a: 'No. All trials are completely free with no credit card required.' },
      { q: 'Can I use my own domain for QR redirect links?', a: 'Yes, custom domains are available on Starter and above.' },
      { q: 'What happens to my QR codes if I cancel?', a: 'Dynamic QR codes stop redirecting, but you can reactivate by upgrading. Static QR codes continue to work forever.' },
      { q: 'Can I generate QR codes in bulk?', a: 'Yes, bulk generation is available via API on Pro and above.' },
    ],
    contact: {
      sales: 'sales@qron.space',
      support: 'support@qron.space',
    },
  });
}
